export const errorList = [
  { code: "901", message: "Invalid Payment Parameters" },

  { code: "902", message: "Invalid Transaction" },

  { code: "903", message: "Invalid Transaction" },

  { code: "107", message: "Call Issuer" },

  { code: "103", message: "Call Issuer" },

  { code: "121", message: "Call Issuer" },

  { code: "123", message: "Call Issuer" },

  { code: "204", message: "Account Restricted" },

  { code: "125", message: "Bad Card" },

  { code: "121", message: "Account Limit Exceeded" },

  { code: "101", message: "Expired Card" },

  { code: "206", message: "Invalid PIN" },

  { code: "117", message: "Incorrect PIN" },

  { code: "126", message: "Incorrect PIN" },

  { code: "920", message: "Incorrect PIN" },

  { code: "904", message: "Invalid Card Type" },

  { code: "905", message: "Invalid Card Type" },

  { code: "110", message: "Invalid Amount" },

  { code: "130", message: "Invalid Amount" },

  { code: "901", message: "Invalid Card Data" },

  { code: "912", message: "Timeout, No Response" },

  { code: "106", message: "Lost or Stolen Card" },

  { code: "208", message: "Lost or Stolen Card" },

  { code: "209", message: "Lost or Stolen Card" },

  { code: "005", message: "System Error" },

  { code: "104", message: "Card Restricted" },

  { code: "200", message: "Invalid or Expired Card" },

  { code: "201", message: "Card Restricted" },

  { code: "907", message: "Issuer Inoperative" },

  { code: "909", message: "Issuer Inoperative" },

  { code: "910", message: "Issuer Inoperative" },

  { code: "911", message: "Issuer Inoperative" },

  { code: "802", message: "Issuer Inoperative" },
  { code: "120", message: "Not Premitted" },
  { code: "100", message: "Do not honor transaction" },
  

];

export const Titles1 = {
  USERNAME: "Username",
  PASSWORD: "Password",
  RMEMBER: "Remember Me",
  FORGOT: "Forgot Password?",
  REGISTER: "Register",
  LOGIN: "Login",
};
export const ErrorsList = [
  {
    key: '',
  }
];
export const transaction_list = [
  {
    id: 1,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2001",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 2,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2002",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 3,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2003",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 4,
    transaction: "Transaction",
    transaction_type: "Refund",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2004",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 5,
    transaction: "Transaction",
    transaction_type: "Refund",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2005",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 6,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2006",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 7,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2007",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 8,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2008",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 9,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "2009",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 10,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20010",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 11,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20011",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 12,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20012",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 13,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20013",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 14,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20014",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
  {
    id: 15,
    transaction: "Transaction",
    transaction_type: "Sale",
    merchant_id: "XXXXXXXXXXX",
    terminal_id: "XXXXXX",
    transaction_no: "20015",
    date: "DD/MM/YYYY",
    time: "HH/MM/SS",
    invalid_no: "XXXXX",
    visa_title: "XXXXXXXXXX",
    account_no: "XXXXXXXXXX",
    amount: "0.00",
    tip_amount: "0.00",
    cashback_amount: "0.00",
    sucharge_amount: "0.00",
    total_amount: "0.00",
    visa_no: "",
    tip_total: "0.00",
    grand_total: "0.00",
    surchage_amount: "",
    invoic_no: "XXXXX",
    ref_no: "XXXXX",
  },
];
export const batch_Content = [
  {
    key: "1",
    titleIntro: "Merchant ID:",
    titleContent: "XXXXXXXXXXX",
  },
  {
    key: "2",
    titleIntro: "Terminal ID:",
    titleContent: "XXXXXXXXXXX",
  },
  {
    key: "3",
    titleIntro: "Batch Number:",
    titleContent: "2001",
  },
  {
    key: "4",
    titleIntro: "Start Date:",
    titleContent: "DD/MM/YYYY",
  },
  {
    key: "5",
    titleIntro: "End Date:",
    titleContent: "DD/MM/YYYY",
  },
  {
    key: "6",
    titleIntro: "Time:",
    titleContent: "HH/MM/SS",
  },
];
export const interac_Totals = [
  {
    key: "1",
    transaction_type: "Sales/Compl",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_type: "Refund",
    count: "50",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_type: "Voids",
    count: "25",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "4",
    transaction_type: "Cashback",
    count: "250",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "5",
    transaction_type: "Surcharge",
    count: "500",
    doller: "$",
    amount: "0.00",
  },
];
export const terminal_Totals = [
  {
    key: "1",
    transaction_type: "Interac",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_type: "Visa",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_type: "MasterCard",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];
export const debitCredit_Totals = [
  {
    key: "1",
    transaction_type: "Sales",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_type: "Tips",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_type: "Surchage",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "4",
    transaction_type: "Refunds",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "5",
    transaction_type: "Voids",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];
export const grand_Totals = [
  {
    key: "1",
    transaction_type: "Sales",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_type: "Tips",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_type: "Cashback",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "4",
    transaction_type: "Surcharge",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "5",
    transaction_type: "Refunds",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "6",
    transaction_type: "Voids",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];
export const tip_DebitTotals = [
  {
    key: "1",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "Interac",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "Visa",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "MasterCard",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];

export const tip_CreditTotals = [
  {
    key: "1",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "Interac",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "2",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "Visa",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
  {
    key: "3",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "MasterCard",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];
export const tip_GrandTotals = [
  {
    key: "1",
    transaction_title: "Debit Totals",
    transaction_type: "Sale",
    card_type: "",
    count: "1500",
    doller: "$",
    amount: "0.00",
  },
];
export const terminal_setting = [
  {
    key: "1",
    title: "Surcharge:",
    content: "Enabled",
  },
  {
    key: "2",
    title: "Surcharge Fee:",
    content: "$0.50",
  },
  {
    key: "3",
    title: "Surcharge %:",
    content: "%1.24",
  },
  {
    key: "4",
    title: "Terminal Language:",
    content: "English",
  },
  {
    key: "5",
    title: "Printer:",
    content: "Disabled",
  },
  {
    key: "6",
    title: "Pre-Print:",
    content: "Disabled",
  },
  {
    key: "7",
    title: "Merchant Copy:",
    content: "Yes",
  },
  {
    key: "8",
    title: "Customer Copy:",
    content: "No",
  },
  {
    key: "9",
    title: "Both:",
    content: "Disabled",
  },
  {
    key: "10",
    title: "Clerk/Server ID",
    content: "Enabled",
  },
  {
    key: "11",
    title: "Invoice Number:",
    content: "Auto Increment",
  },
  {
    key: "12",
    title: "Cashback:",
    content: "%1.24",
  },
  {
    key: "13",
    title: "Manager Password:",
    content: "Disabled",
  },
  {
    key: "14",
    title: "Manual Entry:",
    content: "Disabled",
  },
  {
    key: "15",
    title: "Tip:",
    content: "Disabled",
  },
  {
    key: "16",
    title: "No Tip:",
    content: "Disabled",
  },
  {
    key: "17",
    title: "Amount Other:",
    content: "Disabled",
  },
  {
    key: "18",
    title: "Pre-Set $ Amount:",
    content: "%1.24",
  },
  {
    key: "19",
    title: "Pre-Set % Amount:",
    content: "Disabled",
  },
  {
    key: "20",
    title: "Demo Mode:",
    content: "Disabled",
  },
  {
    key: "21",
    title: "Communication Type:",
    content: "SIM",
  },
];
