export const ErrorCodes = (code) => {
  //todo
  let errorsCodes = {
    "000": "Successful transaction",
    "001":
      "Approve with ID . If transaction was Success , but MCC these is in next list 6010, 4829, 6051, 7995, 7511 – then reason code changes on 001",
    "003": "Successful transaction",
    "005": "System Error",
    "020":
      "Successful transaction; used to indicate a negative balance in Field 4 on a Balance Inquiry",
    "095": "Reconcile Error",
    100: "Do not honor transaction",
    101: "Expired Card",
    103: "Call Issuer",
    104: "Card is restricted",
    105: "Call security",
    106: "Excessive pin failures",
    107: "Call Issuer",
    109: "Invalid merchant ID",
    110: "Cannot process amount",
    111: "Invalid account - retry",
    116: "Insufficient funds - retry",
    117: "Incorrect Pin",
    118: "Forced post, no account on file",
    119: "Transaction not permitted by law",
    120: "Not permitted",
    121: "Account limit exceeded",
    123: "Card limit exceeded",
    125: "Bad Card",
    126: "Pin processing error",
    127: "Service is unnecessary",
    128: "Dynamic Currency Conversion required",
    129: "Invalid currency code",
    130: "Original amount is incorrect",
    131: "Service is inoperative",
    200: "Invalid card",
    201: "Card expired",
    202: "Invalid card",
    203: "Call security",
    204: "Account restricted",
    206: "Invalid Pin",
    208: "Lost Card",
    209: "Stolen Card",
    248: "Partial approval",
    254: "Authorization of the transaction still not complete. Check its status later.",
    327: "Merchant limit exceeded",
    245: "Tips were not credited to the receiver's account",
    331: "Only EC part of transaction is approved",
    600: "POS shall prompt for a second tap or to insert the card",
    601: "POS shall prompt to enter Online PIN without requiring either a second tap or to insert the card",
    901: "Invalid payment parameters",
    902: "Invalid transaction - retry",
    903: "Transaction needs to be entered again",
    904: "The message received was not within standards",
    905: "Issuing institution is unknown",
    907: "Issuer inoperative",
    909: "System malfunction",
    910: "Issuer inoperative",
    911: "SmartVista FE has no knowledge of any attempt to either authorize or deny the transaction.Time out waiting for response",
    912: "Time out waiting for response",
    913: "Duplicate transaction received",
    914: "Could not find the original transaction",
    915: "Amount being reversed is greater than original, or no amount being reversed.",
    920: "Pin processing error",
    923: "Request in progress",
    940: "Pick up card, special condition",
    941: "Failed currency conversion",
  };

  return errorsCodes[code];
};
